apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: log-output-claim
      containers:
        - name: ping-pong
          image: aeriihia/ping-pong:v2
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-files
            mountPath: /usr/src/app/files
